// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
// import type { Database } from "./types";
import type { Database } from "../supabase";

const URL = import.meta.env.VITE_SUPABASE_URL!;
const PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY!;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(URL, PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: "beekon_data",
  },
});
