// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { Database } from "./types";

const URL = "https://apzyfnqlajvbgaejfzfm.supabase.co";
const PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwenlmbnFsYWp2YmdhZWpmemZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mjg3MDAsImV4cCI6MjA2NzAwNDcwMH0.kot73DLrww9kXH5S0LycG9Bqj6v0MGgFA1tr3P_-L8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(URL, PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: "beekon_data",
  },
});
